services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://localhost:5038/api/state-graph
    ports:
      - "5173:8080"
    container_name: zeigdenstaat-frontend
